In [1]:
import torch
from lightning import seed_everything


seed_everything(42)
# torch.manual_seed(42)
# torch.cuda.manual_seed(42)


Seed set to 42


42

In [2]:
linear = [torch.nn.Linear(5, 2), torch.nn.Tanh()]
seq = torch.nn.Sequential(*linear)
x = torch.rand(5)
seq(x)


tensor([0.7205, 0.1115], grad_fn=<TanhBackward0>)

In [2]:
linear = torch.nn.Linear(5, 2)
x = torch.rand(5)
torch.tanh(linear(x))

tensor([0.7205, 0.1115], grad_fn=<TanhBackward0>)

In [6]:
linear2 = torch.nn.Linear(5, 2)
linear2(x)

tensor([-0.3804, -0.4093], grad_fn=<ViewBackward0>)